// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: p2p.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to calculate the shortest route between two peers.
type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPeerId    int32                  `protobuf:"varint,1,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	ToPeerId      int32                  `protobuf:"varint,2,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetFromPeerId() int32 {
	if x != nil {
		return x.FromPeerId
	}
	return 0
}

func (x *RouteRequest) GetToPeerId() int32 {
	if x != nil {
		return x.ToPeerId
	}
	return 0
}

// Response containing the calculated shortest route.
type RouteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           []int32                `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`                                      // Ordered sequence of peer IDs, e.g. [1, 3, 7, 10]
	TotalLatencyMs int64                  `protobuf:"varint,2,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"` // Sum of edge latencies along the path
	Hops           int32                  `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`                                             // Number of hops (len(path) - 1)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RouteResponse) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *RouteResponse) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

// A single cached route entry.
type RouteCacheEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromPeerId     int32                  `protobuf:"varint,1,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	ToPeerId       int32                  `protobuf:"varint,2,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	Path           []int32                `protobuf:"varint,3,rep,packed,name=path,proto3" json:"path,omitempty"`
	TotalLatencyMs int64                  `protobuf:"varint,4,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	Hops           int32                  `protobuf:"varint,5,opt,name=hops,proto3" json:"hops,omitempty"`
	CachedAt       int64                  `protobuf:"varint,6,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"` // Unix timestamp
	TtlSeconds     int32                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteCacheEntry) Reset() {
	*x = RouteCacheEntry{}
	mi := &file_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteCacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteCacheEntry) ProtoMessage() {}

func (x *RouteCacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteCacheEntry.ProtoReflect.Descriptor instead.
func (*RouteCacheEntry) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *RouteCacheEntry) GetFromPeerId() int32 {
	if x != nil {
		return x.FromPeerId
	}
	return 0
}

func (x *RouteCacheEntry) GetToPeerId() int32 {
	if x != nil {
		return x.ToPeerId
	}
	return 0
}

func (x *RouteCacheEntry) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RouteCacheEntry) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *RouteCacheEntry) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *RouteCacheEntry) GetCachedAt() int64 {
	if x != nil {
		return x.CachedAt
	}
	return 0
}

func (x *RouteCacheEntry) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// Request to retrieve the route cache.
type GetCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int32                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheRequest) Reset() {
	*x = GetCacheRequest{}
	mi := &file_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheRequest) ProtoMessage() {}

func (x *GetCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheRequest.ProtoReflect.Descriptor instead.
func (*GetCacheRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *GetCacheRequest) GetRequesterId() int32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

// Response containing all cached route entries.
type GetCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RouteCacheEntry     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResponse) Reset() {
	*x = GetCacheResponse{}
	mi := &file_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResponse) ProtoMessage() {}

func (x *GetCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResponse.ProtoReflect.Descriptor instead.
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *GetCacheResponse) GetEntries() []*RouteCacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Request to invalidate (clear) the route cache.
type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{5}
}

// Response confirming cache invalidation.
type InvalidateCacheResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EntriesCleared int32                  `protobuf:"varint,2,opt,name=entries_cleared,json=entriesCleared,proto3" json:"entries_cleared,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *InvalidateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvalidateCacheResponse) GetEntriesCleared() int32 {
	if x != nil {
		return x.EntriesCleared
	}
	return 0
}

// Information about a peer in the network
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int32                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *PeerInfo) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// Request to register a peer with the bootstrap server
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int32                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_p2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response from bootstrap after registration
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Peers         []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"` // List of known peers to connect to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_p2p_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Request to get list of active peers
type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Max number of peers to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_p2p_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{10}
}

func (x *GetPeersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response with list of active peers
type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_p2p_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{11}
}

func (x *GetPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Ping request for latency measurement
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nano timestamp when ping was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_p2p_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{12}
}

func (x *PingRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Ping response
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponderId   int32                  `protobuf:"varint,1,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nano timestamp when pong was sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_p2p_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetResponderId() int32 {
	if x != nil {
		return x.ResponderId
	}
	return 0
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request to get network graph from a peer
type GraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int32                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRequest) Reset() {
	*x = GraphRequest{}
	mi := &file_p2p_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRequest) ProtoMessage() {}

func (x *GraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRequest.ProtoReflect.Descriptor instead.
func (*GraphRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{14}
}

func (x *GraphRequest) GetRequesterId() int32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

// Network graph response
type GraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NetworkNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*NetworkEdge         `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_p2p_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{15}
}

func (x *GraphResponse) GetNodes() []*NetworkNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphResponse) GetEdges() []*NetworkEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

// A node in the network graph
type NetworkNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkNode) Reset() {
	*x = NetworkNode{}
	mi := &file_p2p_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkNode) ProtoMessage() {}

func (x *NetworkNode) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkNode.ProtoReflect.Descriptor instead.
func (*NetworkNode) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NetworkNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NetworkNode) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// An edge in the network graph (connection between peers)
type NetworkEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int32                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // Measured round-trip latency in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEdge) Reset() {
	*x = NetworkEdge{}
	mi := &file_p2p_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEdge) ProtoMessage() {}

func (x *NetworkEdge) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEdge.ProtoReflect.Descriptor instead.
func (*NetworkEdge) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkEdge) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *NetworkEdge) GetToId() int32 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *NetworkEdge) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// Notification about a new peer joining the network
type NewPeerNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int32                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPeerNotification) Reset() {
	*x = NewPeerNotification{}
	mi := &file_p2p_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPeerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPeerNotification) ProtoMessage() {}

func (x *NewPeerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPeerNotification.ProtoReflect.Descriptor instead.
func (*NewPeerNotification) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{18}
}

func (x *NewPeerNotification) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *NewPeerNotification) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response to a new peer notification
type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_p2p_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{19}
}

func (x *NotifyResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Sha256Hash    string                 `protobuf:"bytes,4,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_p2p_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{20}
}

func (x *ChunkInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChunkInfo) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkInfo) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ChunkInfo) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

type HasChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkRequest) Reset() {
	*x = HasChunkRequest{}
	mi := &file_p2p_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkRequest) ProtoMessage() {}

func (x *HasChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkRequest.ProtoReflect.Descriptor instead.
func (*HasChunkRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{21}
}

func (x *HasChunkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *HasChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type HasChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MightHave     bool                   `protobuf:"varint,1,opt,name=might_have,json=mightHave,proto3" json:"might_have,omitempty"` // Bloom filter result (may false positive)
	Confirmed     bool                   `protobuf:"varint,2,opt,name=confirmed,proto3" json:"confirmed,omitempty"`                  // Actual confirmation after real check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkResponse) Reset() {
	*x = HasChunkResponse{}
	mi := &file_p2p_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkResponse) ProtoMessage() {}

func (x *HasChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkResponse.ProtoReflect.Descriptor instead.
func (*HasChunkResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{22}
}

func (x *HasChunkResponse) GetMightHave() bool {
	if x != nil {
		return x.MightHave
	}
	return false
}

func (x *HasChunkResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type GetBloomFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBloomFilterRequest) Reset() {
	*x = GetBloomFilterRequest{}
	mi := &file_p2p_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBloomFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBloomFilterRequest) ProtoMessage() {}

func (x *GetBloomFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBloomFilterRequest.ProtoReflect.Descriptor instead.
func (*GetBloomFilterRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{23}
}

type GetBloomFilterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BitArray         []byte                 `protobuf:"bytes,1,opt,name=bit_array,json=bitArray,proto3" json:"bit_array,omitempty"`
	NumBits          int32                  `protobuf:"varint,2,opt,name=num_bits,json=numBits,proto3" json:"num_bits,omitempty"`
	NumHashFunctions int32                  `protobuf:"varint,3,opt,name=num_hash_functions,json=numHashFunctions,proto3" json:"num_hash_functions,omitempty"`
	ItemsAdded       int32                  `protobuf:"varint,4,opt,name=items_added,json=itemsAdded,proto3" json:"items_added,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBloomFilterResponse) Reset() {
	*x = GetBloomFilterResponse{}
	mi := &file_p2p_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBloomFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBloomFilterResponse) ProtoMessage() {}

func (x *GetBloomFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBloomFilterResponse.ProtoReflect.Descriptor instead.
func (*GetBloomFilterResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{24}
}

func (x *GetBloomFilterResponse) GetBitArray() []byte {
	if x != nil {
		return x.BitArray
	}
	return nil
}

func (x *GetBloomFilterResponse) GetNumBits() int32 {
	if x != nil {
		return x.NumBits
	}
	return 0
}

func (x *GetBloomFilterResponse) GetNumHashFunctions() int32 {
	if x != nil {
		return x.NumHashFunctions
	}
	return 0
}

func (x *GetBloomFilterResponse) GetItemsAdded() int32 {
	if x != nil {
		return x.ItemsAdded
	}
	return 0
}

type DownloadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunkRequest) Reset() {
	*x = DownloadChunkRequest{}
	mi := &file_p2p_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunkRequest) ProtoMessage() {}

func (x *DownloadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunkRequest.ProtoReflect.Descriptor instead.
func (*DownloadChunkRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{25}
}

func (x *DownloadChunkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type DownloadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sha256Hash    string                 `protobuf:"bytes,2,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunkResponse) Reset() {
	*x = DownloadChunkResponse{}
	mi := &file_p2p_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunkResponse) ProtoMessage() {}

func (x *DownloadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunkResponse.ProtoReflect.Descriptor instead.
func (*DownloadChunkResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{26}
}

func (x *DownloadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadChunkResponse) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

func (x *DownloadChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_p2p_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{27}
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Chunks        []*ChunkInfo           `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_p2p_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{28}
}

func (x *UploadFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadFileResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadFileResponse) GetChunks() []*ChunkInfo {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_p2p_proto protoreflect.FileDescriptor

const file_p2p_proto_rawDesc = "" +
	"\n" +
	"\tp2p.proto\x12\x03p2p\"N\n" +
	"\fRouteRequest\x12 \n" +
	"\ffrom_peer_id\x18\x01 \x01(\x05R\n" +
	"fromPeerId\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x02 \x01(\x05R\btoPeerId\"a\n" +
	"\rRouteResponse\x12\x12\n" +
	"\x04path\x18\x01 \x03(\x05R\x04path\x12(\n" +
	"\x10total_latency_ms\x18\x02 \x01(\x03R\x0etotalLatencyMs\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\x05R\x04hops\"\xe1\x01\n" +
	"\x0fRouteCacheEntry\x12 \n" +
	"\ffrom_peer_id\x18\x01 \x01(\x05R\n" +
	"fromPeerId\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x02 \x01(\x05R\btoPeerId\x12\x12\n" +
	"\x04path\x18\x03 \x03(\x05R\x04path\x12(\n" +
	"\x10total_latency_ms\x18\x04 \x01(\x03R\x0etotalLatencyMs\x12\x12\n" +
	"\x04hops\x18\x05 \x01(\x05R\x04hops\x12\x1b\n" +
	"\tcached_at\x18\x06 \x01(\x03R\bcachedAt\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x05R\n" +
	"ttlSeconds\"4\n" +
	"\x0fGetCacheRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x05R\vrequesterId\"B\n" +
	"\x10GetCacheResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.p2p.RouteCacheEntryR\aentries\"\x18\n" +
	"\x16InvalidateCacheRequest\"\\\n" +
	"\x17InvalidateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fentries_cleared\x18\x02 \x01(\x05R\x0eentriesCleared\"Z\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x05R\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"D\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x05R\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"Q\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05peers\x18\x02 \x03(\v2\r.p2p.PeerInfoR\x05peers\"'\n" +
	"\x0fGetPeersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"7\n" +
	"\x10GetPeersResponse\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.p2p.PeerInfoR\x05peers\"H\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"O\n" +
	"\fPingResponse\x12!\n" +
	"\fresponder_id\x18\x01 \x01(\x05R\vresponderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"1\n" +
	"\fGraphRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x05R\vrequesterId\"_\n" +
	"\rGraphResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.p2p.NetworkNodeR\x05nodes\x12&\n" +
	"\x05edges\x18\x02 \x03(\v2\x10.p2p.NetworkEdgeR\x05edges\"T\n" +
	"\vNetworkNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"Z\n" +
	"\vNetworkEdge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x05R\x04toId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"H\n" +
	"\x13NewPeerNotification\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x05R\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"4\n" +
	"\x0eNotifyResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x85\x01\n" +
	"\tChunkInfo\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\x12\x1f\n" +
	"\vsha256_hash\x18\x04 \x01(\tR\n" +
	"sha256Hash\"K\n" +
	"\x0fHasChunkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"O\n" +
	"\x10HasChunkResponse\x12\x1d\n" +
	"\n" +
	"might_have\x18\x01 \x01(\bR\tmightHave\x12\x1c\n" +
	"\tconfirmed\x18\x02 \x01(\bR\tconfirmed\"\x17\n" +
	"\x15GetBloomFilterRequest\"\x9f\x01\n" +
	"\x16GetBloomFilterResponse\x12\x1b\n" +
	"\tbit_array\x18\x01 \x01(\fR\bbitArray\x12\x19\n" +
	"\bnum_bits\x18\x02 \x01(\x05R\anumBits\x12,\n" +
	"\x12num_hash_functions\x18\x03 \x01(\x05R\x10numHashFunctions\x12\x1f\n" +
	"\vitems_added\x18\x04 \x01(\x05R\n" +
	"itemsAdded\"P\n" +
	"\x14DownloadChunkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"\x8b\x01\n" +
	"\x15DownloadChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsha256_hash\x18\x02 \x01(\tR\n" +
	"sha256Hash\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"M\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"x\n" +
	"\x12UploadFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12&\n" +
	"\x06chunks\x18\x03 \x03(\v2\x0e.p2p.ChunkInfoR\x06chunks2\x88\x01\n" +
	"\x10BootstrapService\x12;\n" +
	"\fRegisterPeer\x12\x14.p2p.RegisterRequest\x1a\x15.p2p.RegisterResponse\x127\n" +
	"\bGetPeers\x12\x14.p2p.GetPeersRequest\x1a\x15.p2p.GetPeersResponse2\x89\x05\n" +
	"\vPeerService\x12+\n" +
	"\x04Ping\x12\x10.p2p.PingRequest\x1a\x11.p2p.PingResponse\x128\n" +
	"\x0fGetNetworkGraph\x12\x11.p2p.GraphRequest\x1a\x12.p2p.GraphResponse\x12>\n" +
	"\rNotifyNewPeer\x12\x18.p2p.NewPeerNotification\x1a\x13.p2p.NotifyResponse\x127\n" +
	"\x0eCalculateRoute\x12\x11.p2p.RouteRequest\x1a\x12.p2p.RouteResponse\x12<\n" +
	"\rGetRouteCache\x12\x14.p2p.GetCacheRequest\x1a\x15.p2p.GetCacheResponse\x12Q\n" +
	"\x14InvalidateRouteCache\x12\x1b.p2p.InvalidateCacheRequest\x1a\x1c.p2p.InvalidateCacheResponse\x127\n" +
	"\bHasChunk\x12\x14.p2p.HasChunkRequest\x1a\x15.p2p.HasChunkResponse\x12I\n" +
	"\x0eGetBloomFilter\x12\x1a.p2p.GetBloomFilterRequest\x1a\x1b.p2p.GetBloomFilterResponse\x12F\n" +
	"\rDownloadChunk\x12\x19.p2p.DownloadChunkRequest\x1a\x1a.p2p.DownloadChunkResponse\x12=\n" +
	"\n" +
	"UploadFile\x12\x16.p2p.UploadFileRequest\x1a\x17.p2p.UploadFileResponseB(Z&github.com/darshan/p2p-fileshare/protob\x06proto3"

var (
	file_p2p_proto_rawDescOnce sync.Once
	file_p2p_proto_rawDescData []byte
)

func file_p2p_proto_rawDescGZIP() []byte {
	file_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)))
	})
	return file_p2p_proto_rawDescData
}

var file_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_p2p_proto_goTypes = []any{
	(*RouteRequest)(nil),            // 0: p2p.RouteRequest
	(*RouteResponse)(nil),           // 1: p2p.RouteResponse
	(*RouteCacheEntry)(nil),         // 2: p2p.RouteCacheEntry
	(*GetCacheRequest)(nil),         // 3: p2p.GetCacheRequest
	(*GetCacheResponse)(nil),        // 4: p2p.GetCacheResponse
	(*InvalidateCacheRequest)(nil),  // 5: p2p.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil), // 6: p2p.InvalidateCacheResponse
	(*PeerInfo)(nil),                // 7: p2p.PeerInfo
	(*RegisterRequest)(nil),         // 8: p2p.RegisterRequest
	(*RegisterResponse)(nil),        // 9: p2p.RegisterResponse
	(*GetPeersRequest)(nil),         // 10: p2p.GetPeersRequest
	(*GetPeersResponse)(nil),        // 11: p2p.GetPeersResponse
	(*PingRequest)(nil),             // 12: p2p.PingRequest
	(*PingResponse)(nil),            // 13: p2p.PingResponse
	(*GraphRequest)(nil),            // 14: p2p.GraphRequest
	(*GraphResponse)(nil),           // 15: p2p.GraphResponse
	(*NetworkNode)(nil),             // 16: p2p.NetworkNode
	(*NetworkEdge)(nil),             // 17: p2p.NetworkEdge
	(*NewPeerNotification)(nil),     // 18: p2p.NewPeerNotification
	(*NotifyResponse)(nil),          // 19: p2p.NotifyResponse
	(*ChunkInfo)(nil),               // 20: p2p.ChunkInfo
	(*HasChunkRequest)(nil),         // 21: p2p.HasChunkRequest
	(*HasChunkResponse)(nil),        // 22: p2p.HasChunkResponse
	(*GetBloomFilterRequest)(nil),   // 23: p2p.GetBloomFilterRequest
	(*GetBloomFilterResponse)(nil),  // 24: p2p.GetBloomFilterResponse
	(*DownloadChunkRequest)(nil),    // 25: p2p.DownloadChunkRequest
	(*DownloadChunkResponse)(nil),   // 26: p2p.DownloadChunkResponse
	(*UploadFileRequest)(nil),       // 27: p2p.UploadFileRequest
	(*UploadFileResponse)(nil),      // 28: p2p.UploadFileResponse
}
var file_p2p_proto_depIdxs = []int32{
	2,  // 0: p2p.GetCacheResponse.entries:type_name -> p2p.RouteCacheEntry
	7,  // 1: p2p.RegisterResponse.peers:type_name -> p2p.PeerInfo
	7,  // 2: p2p.GetPeersResponse.peers:type_name -> p2p.PeerInfo
	16, // 3: p2p.GraphResponse.nodes:type_name -> p2p.NetworkNode
	17, // 4: p2p.GraphResponse.edges:type_name -> p2p.NetworkEdge
	20, // 5: p2p.UploadFileResponse.chunks:type_name -> p2p.ChunkInfo
	8,  // 6: p2p.BootstrapService.RegisterPeer:input_type -> p2p.RegisterRequest
	10, // 7: p2p.BootstrapService.GetPeers:input_type -> p2p.GetPeersRequest
	12, // 8: p2p.PeerService.Ping:input_type -> p2p.PingRequest
	14, // 9: p2p.PeerService.GetNetworkGraph:input_type -> p2p.GraphRequest
	18, // 10: p2p.PeerService.NotifyNewPeer:input_type -> p2p.NewPeerNotification
	0,  // 11: p2p.PeerService.CalculateRoute:input_type -> p2p.RouteRequest
	3,  // 12: p2p.PeerService.GetRouteCache:input_type -> p2p.GetCacheRequest
	5,  // 13: p2p.PeerService.InvalidateRouteCache:input_type -> p2p.InvalidateCacheRequest
	21, // 14: p2p.PeerService.HasChunk:input_type -> p2p.HasChunkRequest
	23, // 15: p2p.PeerService.GetBloomFilter:input_type -> p2p.GetBloomFilterRequest
	25, // 16: p2p.PeerService.DownloadChunk:input_type -> p2p.DownloadChunkRequest
	27, // 17: p2p.PeerService.UploadFile:input_type -> p2p.UploadFileRequest
	9,  // 18: p2p.BootstrapService.RegisterPeer:output_type -> p2p.RegisterResponse
	11, // 19: p2p.BootstrapService.GetPeers:output_type -> p2p.GetPeersResponse
	13, // 20: p2p.PeerService.Ping:output_type -> p2p.PingResponse
	15, // 21: p2p.PeerService.GetNetworkGraph:output_type -> p2p.GraphResponse
	19, // 22: p2p.PeerService.NotifyNewPeer:output_type -> p2p.NotifyResponse
	1,  // 23: p2p.PeerService.CalculateRoute:output_type -> p2p.RouteResponse
	4,  // 24: p2p.PeerService.GetRouteCache:output_type -> p2p.GetCacheResponse
	6,  // 25: p2p.PeerService.InvalidateRouteCache:output_type -> p2p.InvalidateCacheResponse
	22, // 26: p2p.PeerService.HasChunk:output_type -> p2p.HasChunkResponse
	24, // 27: p2p.PeerService.GetBloomFilter:output_type -> p2p.GetBloomFilterResponse
	26, // 28: p2p.PeerService.DownloadChunk:output_type -> p2p.DownloadChunkResponse
	28, // 29: p2p.PeerService.UploadFile:output_type -> p2p.UploadFileResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_p2p_proto_init() }
func file_p2p_proto_init() {
	if File_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_proto_depIdxs,
		MessageInfos:      file_p2p_proto_msgTypes,
	}.Build()
	File_p2p_proto = out.File
	file_p2p_proto_goTypes = nil
	file_p2p_proto_depIdxs = nil
}
